# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Noble Factor. All rights reserved.
# Redistribution and use in source and binary forms, with or without modification, are permitted under the terms of the MIT License.

services:
  homebridge:
    image: ${HOMEBRIDGE_IMAGE}
    container_name: ${CONTAINER_HOSTNAME}
    mac_address: ${MAC_ADDRESS:-}
    hostname: ${CONTAINER_HOSTNAME}
    domainname: ${CONTAINER_DOMAIN_NAME}
    networks:
      docker_network:
        ipv4_address: ${IP_ADDRESS:-}
    restart: always
    cap_add:
      - SYS_ADMIN 
    devices:
      - /dev/fuse:/dev/fuse:rwm
    volumes:
      - type: bind
        source: ${CONTAINER_VOLUME}
        target: /homebridge
        bind:
            propagation: rprivate
    environment:
      NOBLEFACTOR_HOMEBRIDGE_LOCATION: ${LOCATION}
      PUID: 1000  # first user created on most systems
      PGID: 0     # root group => can elevate permissions if needed
    healthcheck:
      test: [ "CMD", "curl",
        "--fail",
        "--insecure",
        "--output", "/dev/null",
        "--show-error",
        "--silent",
        "--write-out", "Total time: %{time_total}s\\n",
        "https://localhost" ]
      interval: 60s
      retries: 5
      start_period: 30s
      timeout: 2s
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    security_opt:
      - apparmor:unconfined
networks:
  docker_network:
     external: true
     name: ${NETWORK_NAME}
